---
abstract: 'Expand abbreviations and acronyms.'
author:
  - 'Ronaldo Ferreira de Lima aka jimmy <jimmy.tty@gmail.com>'
build_requires:
  Data::Dumper: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::Util: '0'
  Test::More: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.03'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-UnAbbrev
requires:
  Carp: '0'
  English: '0'
  File::Find: '0'
  File::ShareDir::ProjectDistDir: '0'
  File::Spec::Functions: '0'
  IO::File: '0'
  Moo: '0'
  charnames: '0'
  common::sense: '0'
  perl: '5.010'
version: '0.001'
